server:
  port: 9095
  servlet:
    context-path: /ui
  session:
    cookie:
      name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:9095/auth/oauth/token
      userAuthorizationUri: http://localhost:9095/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:9095/auth/user/me
spring:
  thymeleaf:
    cache: false